# Generated by Django 4.0.3 on 2022-04-08 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='course_name')),
            ],
            options={
                'ordering': ['updated_at', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='lection_name')),
                ('lection_text', models.CharField(max_length=100, verbose_name='lection_name')),
            ],
            options={
                'ordering': ['updated_at', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='test_name')),
                ('question', models.JSONField()),
                ('lection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lections')),
            ],
            options={
                'ordering': ['updated_at', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lection_active', models.BooleanField()),
                ('test_active', models.BooleanField()),
                ('answer', models.JSONField()),
                ('assignment', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('lection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lections')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.tests')),
            ],
            options={
                'ordering': ['updated_at', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='lection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lections'),
        ),
    ]
