# Generated by Django 4.0.3 on 2022-04-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lections_lection_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lections',
            name='lection_text',
            field=models.TextField(blank=True, null=True, verbose_name='lection_text'),
        ),
    ]
