# Generated by Django 4.0.3 on 2022-04-08 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lections_lection_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='lecture_name')),
                ('lecture_text', models.TextField(blank=True, null=True, verbose_name='lecture_text')),
            ],
            options={
                'ordering': ['updated_at', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='results',
            old_name='lection_active',
            new_name='lecture_active',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='lection',
        ),
        migrations.RemoveField(
            model_name='results',
            name='lection',
        ),
        migrations.RemoveField(
            model_name='tests',
            name='lection',
        ),
        migrations.DeleteModel(
            name='Lections',
        ),
        migrations.AddField(
            model_name='courses',
            name='lecture',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lectures'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='lecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.lectures'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tests',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lectures'),
            preserve_default=False,
        ),
    ]
