# Generated by Django 4.0.3 on 2022-04-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_test_test_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='name',
            new_name='lecture_name',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='test_name',
        ),
    ]
