# Generated by Django 4.0.3 on 2022-04-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_name_course_course_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.AddField(
            model_name='course',
            name='stage_num',
            field=models.IntegerField(default=1, verbose_name='stage_num'),
            preserve_default=False,
        ),
    ]
