# Generated by Django 4.0.3 on 2022-04-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_course_course_name_course_stage_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='stage_num',
            field=models.IntegerField(unique=True, verbose_name='stage_num'),
        ),
    ]
